server:
  servlet:
    #  定义项目的访问路径
    context-path: /consumer
    #定义端口号
  port: 7006
spring:
  application:
    #定义应用名称，即服务名称
    name: consumer-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 15
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka,http://localhost:5070/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #eureka服务端自我保护机制开启后就使用默认的就ok了
    #客户端向服务端发送心跳时间间隔,开发时设置的小一些，保证关闭服务后能即时踢出注册中心
    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过踢出
    lease-expiration-duration-in-seconds: 2
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
