#http://localhost:7009/test-config-client-dev.yml  命名规则：  服务名-环境.yml

spring:
  application:
    name: config-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gl-git/gkconfig.git
          # 该git地址中配置的路径 文件夹
          search-paths:
            -  gkconfig
          default-label: master
          username: 962422150@qq.com
          password: gl18882341560
server:
  port: 7009
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5060/eureka,http://localhost:5070/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
